<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Configurations>Debug;Release;debug libs</Configurations>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Version>1.0.0.4</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Serilog configuration extensions</Title>
    <PackageOutputPath>$(SolutionDir)\packages</PackageOutputPath>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <Authors>innasolp</Authors>
    <RepositoryUrl>https://github.com/innasolp/LogExtensions</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="CustomJsonConfigurationProvider" Version="1.0.1" />
	<PackageReference Include="CustomConfigurationProvider" Version="1.0.1" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist $(ProjectDir)\..\..\Libs\Log mkdir  $(ProjectDir)\..\..\Libs\Log&#xD;&#xA;set logDir=$(ProjectDir)\..\..\Libs\Log\&#xD;&#xA;set outDir=%25logDir%25\Serilog.Configuration.Extensions\&#xD;&#xA;if not exist &quot;%25outDir%25&quot; mkdir  &quot;%25outDir%25&quot;&#xD;&#xA;xcopy /E /Y  &quot;$(TargetDir)&quot; &quot;%25outDir%25&quot;&#xD;&#xA;set currentDir=$(SolutionDir)\Libs\Log\Serilog.Configuration.Extensions\&#xD;&#xA;if not exist &quot;%25currentDir%25&quot; mkdir  &quot;%25currentDir%25&quot;&#xD;&#xA;xcopy /E /Y  &quot;$(TargetDir)&quot; &quot;%25currentDir%25&quot;" />
  </Target>

</Project>
