name: X AI Code Review by nikita filonov (via Tailscale)

on:
  workflow_dispatch: 
    inputs:
      agent_mode:
        type: boolean
        default: true
      rg_enabled:
        description: 'ripgrep for AI-gent when agent mode enabled'
        type: boolean
        default: true    
      pr_number:
        description: 'Input pull request number'
        required: true
        type: string
      provider:
        description: 'Select provider'
        required: true
        default: 'LLAMA'
        type: choice
        options:
          - 'LLAMA'
          - 'OPENROUTER' 
          - 'OLLAMA' 
          - 'PGSGROVE'
          - 'GPTUNNEL'
          - 'AITUNNEL'
      model_name:
        description: 'Select model'
        required: true
        default: 'qwen2.5-coder:7b'
        type: choice
        options:
          - 'qwen2.5-coder:7b' 
          - 'qwen2.5-coder:14b'
          - 'qwen2.5-coder:3b'
          - 'qwen/qwen3.8-27b:free'
          - 'deepseek-v4-pro'
          - 'deepseek-v4-pro-0813'
          - 'deepseek-v4.1-flash'
      review-command:
        type: choice
        default: 'run'
        required: true
        options:
          - run
          - run-inline
          - run-context
          - run-summary
          - run-inline-reply
          - run-summary-reply
          - clear-inline
          - clear-summary
      per_page:
        type: string
        required: true 
        default: '30'
      max_pages:
        type: string
        required: true 
        default: '5'     

jobs:  
          
  ai-review-openai:   
     uses : innasolp/GithubActions/.github/workflows/nikita-filonov-ai-review.yaml@main
     with:
       agent-mode: ${{ inputs.agent_mode }}
       rg_enabled: ${{ inputs.rg_enabled }}
       pull-request-number: ${{ inputs.pr_number }}
       model_name: ${{ inputs.model_name }}
       provider: ${{ inputs.provider }}
       review-command: ${{ inputs.review-command }}
       per_page: ${{ inputs.per_page }}
       max_pages: ${{ inputs.max_pages }}
     secrets: inherit 
     
